### ISSUE TITLE
Logback: Logging Exceptions with null message cause NullPointerException thrown by LoggingAppender and no log issued

### ISSUE THREAD

**Issue by nexteam-silviot** [googleapis/java-logging-logback#248]
Hello,
we're using the latest java-logging-logback library for our Google Cloud infrastructure with the LogbackAppender that appends on Stackdriver.

&lt;dependency&gt;
    &lt;groupId&gt;com.google.cloud&lt;/groupId&gt;
    &lt;artifactId&gt;google-cloud-logging-logback&lt;/artifactId&gt;
    &lt;version&gt;0.118.5-alpha&lt;/version&gt;
&lt;/dependency&gt;

When logging particular Exceptions with a null message the class com.google.cloud.logging.logback.LoggingAppender throws a NullPointerException and the log is not printed on the appender.

Putting the logback configuration in debug mode, on stdout an appender Exception is printed but the previously logged Exception is lost.

#### Steps to reproduce

1. Use LoggingAppender and enable debug mode

&lt;configuration debug="true"&gt;
...
&lt;appender name="CLOUD" class="com.google.cloud.logging.logback.LoggingAppender"&gt;
	&lt;!-- Optional : filter logs at or above a level --&gt;
	&lt;filter class="ch.qos.logback.classic.filter.ThresholdFilter"&gt;
		&lt;level&gt;DEBUG&lt;/level&gt;
	&lt;/filter&gt;
	&lt;log&gt;test&lt;/log&gt;
	&lt;flushLevel&gt;DEBUG&lt;/flushLevel&gt;
&lt;/appender&gt;

2. Call logger.error()
```java
logger.error(new NullPointerException());
```

3. You will get a NullPointerException from LoggingAppender on stdout and the occurred Exception is not logged

19:33:00,377 |-ERROR in com.google.cloud.logging.logback.LoggingAppender[CLOUD] - Appender [CLOUD] failed to append. java.lang.NullPointerException
        at java.lang.NullPointerException
        at      at java.base/java.lang.StringBuilder.<init>(Unknown Source)
        at      at com.google.cloud.logging.logback.LoggingAppender.logEntryFor(LoggingAppender.java:294)
        at      at com.google.cloud.logging.logback.LoggingAppender.append(LoggingAppender.java:231)
        at      at com.google.cloud.logging.logback.LoggingAppender.append(LoggingAppender.java:79)
        at      at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at      at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
        at      at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at      at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at      at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:422)
        at      at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:384)
        at      at ch.qos.logback.classic.Logger.error(Logger.java:539)
        at      at com.test.logger.impl.Slf4jLogger.error(Slf4jLogger.java:140)
        at      at com.test.resources.PingResource.ping(PingResource.java:41)
        at      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

#### Where the Issue is located

The issue can be found in the LoggingAppender source, in logEntryFor function (row 294):

```java
  private LogEntry logEntryFor(ILoggingEvent e) {
    StringBuilder payload = new StringBuilder(e.getFormattedMessage()).append('\n');
    writeStack(e.getThrowableProxy(), "", payload);

    Level level = e.getLevel();
    Severity severity = severityFor(level);
```

At the first row, StringBuilder constructor throws NullPointerException because it expects a not-null string.

#### Fix suggestion

A way to fix the issue is to instantiate StringBuilder with no parameters then call append() passing the formatted message as append() is null safe.

```java
  private LogEntry logEntryFor(ILoggingEvent e) {
    StringBuilder payload = new StringBuilder().append(e.getFormattedMessage()).append('\n');
    writeStack(e.getThrowableProxy(), "", payload);

    Level level = e.getLevel();
    Severity severity = severityFor(level);
```

Thank you for your attention!

**Comment by athakor** [comment]
@nexteam-silvio Thanks for these issue, I am able to reproduce it and will raise PR soon.
