### ISSUE TITLE
Random RuntimeException while executing runnable CallbackListener

### ISSUE THREAD

**Issue by knyttl** [googleapis/java-logging-logback#249]
When using logback, I am getting random messages in the logs:

```
SEVERE: RuntimeException while executing runnable CallbackListener{com.google.api.core.ApiFutures$1@69dd2298} with executor MoreExecutors.directExecutor()
```

and then also:

```
java.lang.RuntimeException: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 49.999792464s. [buffered_nanos=50999356505, waiting_for_connection]
	at com.google.cloud.logging.LoggingImpl$7.onFailure(LoggingImpl.java:615)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1041)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:100)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:126)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.gax.rpc.BatchedFuture.setException(BatchedFuture.java:55)
	at com.google.api.gax.rpc.BatchedRequestIssuer.sendResult(BatchedRequestIssuer.java:84)
	at com.google.api.gax.rpc.BatchExecutor$1.onFailure(BatchExecutor.java:98)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
```

Does it mean, there are some messages lost? Can this be safely ignored? 

I can see these pretty regularly.

**Comment by simonz130** [comment]
Yes, possibly some messages are lost. Where do you run your code?

Also, regardless, wanted to mention that we'll be upgrading the batching logic in Q3. it's going to be part of the java-logging library instead of the com.google.api.gax library. That should make this issue disappear but I would still like to know where you run your code.

**Comment by knyttl** [comment]
I solved this using "sync" settings instead of default "async". This happens in Google Cloud Functions.

**Comment by minherz** [comment]
@knyttl i am closing the issue. feel free to reopen if you feel the question wasn't addressed.

**Comment by lijufeng2016** [comment]
> I solved this using "sync" settings instead of default "async". This happens in Google Cloud Functions.

could you tell me the config key?I am facing this problem

**Comment by knyttl** [comment]
```kotlin
private val logging = LoggingOptions
        .getDefaultInstance()
        .getService()

    // this must be set to true for Cloud Functions
    override var synchronicity: Synchronicity
        get() = logging.writeSynchronicity
        set(value) {
            logging.writeSynchronicity = value
        }
```

**Comment by minherz** [comment]
@knyttl It is possible to configure the Synchronization flag in the logback configuration. To make writing synchronous, use:
```xml
<writeSynchronicity>SYNC</writeSynchronicity>
```

**Comment by knyttl** [comment]
I don't use logback, I log directly via the logging api.
