### ISSUE TITLE
throwProxy.getSuppressed() is skipped

### ISSUE THREAD

**Issue by leoiii12** [googleapis/java-logging-logback#296]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
We are using spring reactor webflux to develop our web application. The original stacktrace produced is not user-friendly, so the reactor team has designed a java agent to enhance the logs, this is called `production-ready assembly back-tracing`.

https://projectreactor.io/docs/core/release/reference/#reactor-tools-debug
https://github.com/reactor/reactor-tools#reactor-debug-agent---production-ready-assembly-back-tracing

Here is the produced log in stdout.

```
java.lang.IndexOutOfBoundsException: Source emitted more than one item
  at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:129)
   ...
  at java.lang.Thread.run(Thread.java:748)
  Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoSingle] :
  reactor.core.publisher.Flux.single(Flux.java:7380)
  foo.Bar.baz(Bar.java:22)
Error has been observed by the following operator(s):
  |_	Flux.single ⇢ foo.Bar.baz(Bar.java:22)
```

You can see the user-friendly message is marked `Suppressed: `.
However, the produced stacktrace and the log entry in the google cloud logging has only

```
java.lang.IndexOutOfBoundsException: Source emitted more than one item
  at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:129)
   ...
  at java.lang.Thread.run(Thread.java:748)
```

I found the elements after `Suppressed: ` are all skipped while these elements are critical for our debugging experience.

The cause is the implementation of `com.google.cloud.logging.logback.LoggingAppender#writeStack` does not respect the `throwProxy.getSuppressed()` which all the skipped log elements are stored here.

**Describe the solution you'd like**
Add an option to respect `throwProxy.getSuppressed()`.

**Describe alternatives you've considered**
I have come up a workaround by using an enhancer.

```java
import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.spi.IThrowableProxy;
import ch.qos.logback.classic.spi.StackTraceElementProxy;
import com.google.cloud.logging.LogEntry;
import com.google.cloud.logging.Payload;
import com.google.cloud.logging.Severity;
import com.google.cloud.logging.logback.LoggingAppender;
import com.google.cloud.logging.logback.LoggingEventEnhancer;

import java.util.HashMap;
import java.util.Map;

public class SuppressedEnhancer implements LoggingEventEnhancer
{
	@Override
	public void enhanceLogEntry(LogEntry.Builder builder, ILoggingEvent e)
	{
		StringBuilder payload = new StringBuilder().append(e.getFormattedMessage()).append('\n');
		writeStack(e.getThrowableProxy(), "", payload);

		Level level = e.getLevel();
		Severity severity = severityFor(level);

		Map<String, Object> jsonContent = new HashMap<>();
		jsonContent.put("message", payload.toString().trim());
		if (severity == Severity.ERROR)
		{
			jsonContent.put("@type", "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent");
		}

		builder.setPayload(Payload.JsonPayload.of(jsonContent));
	}

	/**
	 * @param throwProxy
	 * @param prefix
	 * @param payload
	 * @see LoggingAppender#writeStack(ch.qos.logback.classic.spi.IThrowableProxy, java.lang.String, java.lang.StringBuilder)
	 */
	@SuppressWarnings("JavadocReference")
	private static void writeStack(IThrowableProxy throwProxy, String prefix, StringBuilder payload)
	{
		if (throwProxy == null)
		{
			return;
		}
		payload
				.append(prefix)
				.append(throwProxy.getClassName())
				.append(": ")
				.append(throwProxy.getMessage())
				.append('\n');
		StackTraceElementProxy[] trace = throwProxy.getStackTraceElementProxyArray();
		if (trace == null)
		{
			trace = new StackTraceElementProxy[0];
		}

		int commonFrames = throwProxy.getCommonFrames();
		int printFrames = trace.length - commonFrames;
		for (int i = 0; i < printFrames; i++)
		{
			payload.append("    ").append(trace[i]).append('\n');
		}
		if (commonFrames != 0)
		{
			payload.append("    ... ").append(commonFrames).append(" common frames elided\n");
		}

		writeStack(throwProxy.getCause(), "caused by: ", payload);

               // Diff
               // Diff
               // Diff
               // Diff
               // Diff
               // Diff
               // Diff
               // Diff
               // Diff
		for (IThrowableProxy throwableProxy : throwProxy.getSuppressed())
		{
			writeStack(throwableProxy, "suppressed: ", payload);
		}
	}

	/**
	 * @param level
	 * @return
	 * @see LoggingAppender#severityFor(ch.qos.logback.classic.Level)
	 */
	@SuppressWarnings("JavadocReference")
	private static Severity severityFor(Level level)
	{
		switch (level.toInt())
		{
			// TRACE
			case 5000:
				return Severity.DEBUG;
			// DEBUG
			case 10000:
				return Severity.DEBUG;
			// INFO
			case 20000:
				return Severity.INFO;
			// WARNING
			case 30000:
				return Severity.WARNING;
			// ERROR
			case 40000:
				return Severity.ERROR;
			default:
				return Severity.DEFAULT;
		}
	}
}
```

**Additional context**
Any other context or screenshots about the feature request.

**Comment by minherz** [comment]
Thank you. We will look into it.

**Comment by minherz** [comment]
We have reviewed the problem description. Unfortunately, there is no standard about how to treat the stack trace. While the described heuristic can be a good fit for your use case it can be incorrect in another. It is less desirable to change the existing behavior since it is in use by many active customers. Since the library already provides the solution via the use of the enhancers, we will close this issue.
If you have additional information on the subject, feel free to reopen the issue.
